// src/services/api.js
// ─────────────────────────────────────────────────────────────────────────────
//  CENTRALIZED API SERVICE
//  PERF FIXES (previous revision):
//   1. API_TIMEOUT 15s → 10s. 15s is too long to wait for a failed request —
//      user perceives the app as "hung" for the full window. 10s is enough
//      for genuinely slow-but-OK responses on 3G, and fails fast on dead links.
//   2. console.log/warn calls now no-op when IS_DEV is false. Each console.log
//      in RN is a JS-to-native bridge call — under heavy load (sync + tick +
//      list scroll) these add up. Stripping them in prod removes ~15 calls per
//      API request (request log + success log + error path).
//
//  FIX (this revision) — recording upload "network error":
//   The axios instance default header 'Content-Type': 'application/json'
//   was bleeding into multipart/form-data upload requests in callLogsApi.js.
//   Setting 'Content-Type': undefined per-request does NOT clear an instance-
//   level default — axios merges headers and the instance value always wins.
//   The server received 'application/json' with a binary multipart body and
//   could not parse it.
//
//   Fix: callLogsApi.uploadRecording() now uses native fetch() directly so it
//   is completely isolated from this axios instance. No change needed here —
//   this comment documents WHY the upload bypasses this client.
//
//   Additionally: removed 'Content-Type': 'application/json' from instance
//   defaults and moved it to the request interceptor where it is set ONLY
//   when the request body is not a FormData object. This is a belt-and-
//   suspenders guard so even future axios-based uploads won't hit this bug.
// ─────────────────────────────────────────────────────────────────────────────

import axios from 'axios';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { BASE_URL, API_TIMEOUT, IS_DEV } from '../config/config';

// PERF FIX: dev-only logger. Calls compile away to nothing when IS_DEV=false
// (no string concatenation, no bridge crossing). Use these instead of
// raw console.log throughout this file.
const dlog  = IS_DEV ? (...a) => console.log(...a)  : () => {};
const dwarn = IS_DEV ? (...a) => console.warn(...a) : () => {};

// ─── Axios instance ───────────────────────────────────────────────────────────
// FIX: Content-Type removed from instance defaults — it is now set
// conditionally in the request interceptor below so FormData requests
// never receive the wrong Content-Type.
const api = axios.create({
  baseURL: BASE_URL,
  timeout: API_TIMEOUT, // from config — single source of truth
  headers: {
    Accept: 'application/json',
    // NOTE: Content-Type is intentionally NOT set here.
    // It is applied per-request in the interceptor below.
  },
});

// ─── Request interceptor ─────────────────────────────────────────────────────
api.interceptors.request.use(
  async (config) => {
    // Attach auth token
    try {
      const token = await AsyncStorage.getItem('auth_token');
      if (token) {
        config.headers.Authorization = `Bearer ${token}`;
      }
    } catch {
      // No token — proceed unauthenticated
    }

    // FIX: Only set Content-Type to application/json when the body is NOT
    // FormData. For FormData, the boundary must be auto-generated by the
    // network layer — never set it manually.
    if (!(config.data instanceof FormData)) {
      config.headers['Content-Type'] = 'application/json';
    }

    dlog(`[API →] ${config.method?.toUpperCase()} ${config.baseURL}${config.url}`);
    return config;
  },
  (error) => Promise.reject(error),
);

// ─── Response interceptor ────────────────────────────────────────────────────
api.interceptors.response.use(
  (response) => {
    dlog(`[API ✓] ${response.status} ${response.config.url}`);
    return response;
  },
  async (error) => {
    const status  = error.response?.status;
    const message = error.response?.data?.message || '';

    if (status === 401) {
      const isAuthError =
        message.toLowerCase().includes('invalid') ||
        message.toLowerCase().includes('expired') ||
        message.toLowerCase().includes('jwt') ||
        message.toLowerCase().includes('no token') ||
        message.toLowerCase().includes('unauthorized');

      if (isAuthError) {
        try {
          await AsyncStorage.removeItem('auth_token');
          await AsyncStorage.removeItem('auth_user');
        } catch { /* ignore */ }
      }
    }

    error.userMessage = buildUserMessage(error);
    dwarn(`[API ✗] ${error.userMessage}`, error.response?.data);
    return Promise.reject(error);
  },
);

// ─── User-friendly error messages ────────────────────────────────────────────
function buildUserMessage(error) {
  if (!error.response) {
    if (error.code === 'ECONNABORTED')
      return 'Request timed out. Check your backend is running and reachable.';
    if (error.message?.includes('Network Error'))
      return `Cannot reach the server at ${BASE_URL}. Make sure:\n` +
             `1. Backend is running (npm run dev)\n` +
             `2. Your device and PC are on the same WiFi\n` +
             `3. The IP in src/config/config.js matches your PC's LAN IP`;
    return 'Network error. Please try again.';
  }

  const { status, data } = error.response;
  const serverMsg = data?.message || data?.error || '';

  switch (status) {
    case 400: return serverMsg || 'Invalid request. Please check your input.';
    // A 401 on the LOGIN request means bad credentials (or the backend
    // rejecting the account/device) — NOT an expired session. Prefer the
    // server's own message ("Invalid email or password", etc.) so the login
    // screen shows the real reason. Only fall back to the session-expired
    // wording when the server sends no message, which is the case for a
    // genuinely expired token on an already-authenticated request.
    case 401: return serverMsg || 'Session expired. Please log in again.';
    case 403: return 'You do not have permission to do that.';
    case 404: return 'Resource not found.';
    case 422: return serverMsg || 'Validation failed.';
    case 429: return 'Too many requests. Please wait a moment.';
    case 500: return 'Server error. Please try again later.';
    case 503: return 'Server is temporarily unavailable.';
    default:  return serverMsg || `Unexpected error (${status}).`;
  }
}

// ─── apiRequest helper ───────────────────────────────────────────────────────
export async function apiRequest(
  endpoint,
  method = 'GET',
  body = null,
  token = null,
  params = null,
  headers = {},
) {
  const config = {
    url: endpoint,
    method: method.toLowerCase(),
    params,
    headers,
  };
  if (token) {
    config.headers = { ...config.headers, Authorization: `Bearer ${token}` };
  }
  if (body) {
    config.data = body;
  }
  const response = await api(config);
  return response.data;
}

// ─── Health check ────────────────────────────────────────────────────────────
export async function checkHealth() {
  try {
    const res = await api.get('/health', { timeout: 5000 });
    dlog('[Health] ✅ Backend reachable:', res.data);
    return { ok: true, data: res.data };
  } catch (error) {
    dwarn('[Health] ❌ Backend unreachable:', error.userMessage || error.message);
    return { ok: false, error: error.userMessage || error.message };
  }
}

// ─── Warm-up ping ────────────────────────────────────────────────────────────
// Render's free tier sleeps after inactivity and takes 30–60s to cold-start.
// The FIRST real request would otherwise hit a sleeping server and time out at
// API_TIMEOUT (15s) before it finishes waking — making the app feel frozen on
// open. Fire this on app launch (fire-and-forget) so the server starts spinning
// up while the user is still on the splash/login screen; by the time real
// endpoints are hit it's already awake. Uses a long timeout + one retry
// specifically to survive a cold start (unlike checkHealth's short 5s timeout).
export async function warmUpBackend() {
  const COLD_START_TIMEOUT = 60000; // 60s — long enough to outlast a full cold start
  for (let attempt = 1; attempt <= 2; attempt++) {
    try {
      await api.get('/health', { timeout: COLD_START_TIMEOUT });
      dlog(`[WarmUp] ✅ Backend awake (attempt ${attempt})`);
      return true;
    } catch (e) {
      dwarn(`[WarmUp] attempt ${attempt} failed:`, e?.message);
    }
  }
  return false;
}

export const BASE_URL_EXPORT = BASE_URL;
export default api;